/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package midproject1;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

// Import DAO classes
import midproject1.dao.TaskDao;
import midproject1.dao.UserDao;

/**
 * ViewAllTaskFrame for admins to view, query, and update all tasks in the system.
 */
public class ViewAllTaskFrame extends javax.swing.JFrame {

    private Admin admin; // The Admin object, potentially passed from AdminDashboardFrame
    private TaskDao taskDao; // DAO for task operations
    private UserDao userDao; // DAO for user operations (to find users for assignment)

    /**
     * Constructor with Admin parameter.
     * Initializes components, DAOs, and fills the task table.
     * @param admin The Admin object for context and navigation.
     */
    public ViewAllTaskFrame(Admin admin) {
        this.admin = admin;
        initComponents();
        initializeDaos(); // Initialize DAO instances
        fillTable(); // Populate the table with all tasks
    }

    /**
     * Default constructor.
     * Initializes components and DAOs, for cases where an Admin object isn't explicitly passed.
     */
    public ViewAllTaskFrame() {
        initComponents();
        initializeDaos();
        // If accessed without an Admin object, 'admin' field will be null.
        // It's recommended to always pass the admin object for proper navigation back.
        fillTable();
    }

    /**
     * Initializes DAO instances for database operations.
     */
    private void initializeDaos() {
        taskDao = new TaskDao();
        userDao = new UserDao();
    }

    /**
     * Fills the jTable1 with all tasks from the database.
     * Includes Task ID as a hidden first column for internal use.
     */
    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        // Fetch all tasks from the database using TaskDao
        List<Task> allTasks = taskDao.findAll();

        for (Task task : allTasks) {
            // Ensure the AssignedTo user exists or display "N/A"
            String assignedUsername = task.getAssignedUsername() != null ? task.getAssignedUsername() : "N/A";
            
            // Add task data to the table: ID (hidden), Task Name, Assigned To, Book Title, Deadline, Status
            model.addRow(new Object[]{ // Hidden ID
                task.getName(),
                task.getAssignedTo(),
                task.getBookTitle(),
                task.getDeadline() != null ? task.getDeadline().toString() : "N/A", // Convert LocalDate to String
                task.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtSearchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnQuery = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUpdateTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Search :");

        txtSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchFieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task Name", "Assigned To", "Book Title ", "Deadline", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnQuery.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuery.setForeground(new java.awt.Color(255, 51, 51));
        btnQuery.setText(" Query Selected Task ");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        btnBack3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack3.setText("Back");
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnLogout3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout3.setText("Log out ");
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("View All Tasks");

        btnUpdateTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdateTable.setForeground(new java.awt.Color(0, 153, 51));
        btnUpdateTable.setText("Update");
        btnUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnQuery)
                        .addGap(38, 38, 38))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogout3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUpdateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdateTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout3)
                    .addComponent(btnBack3))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     // Action for the search field
    private void txtSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchFieldActionPerformed
        String searchText = txtSearchField.getText().toLowerCase().trim();
        List<Task> filteredTasks = new java.util.ArrayList<>();

        List<Task> allTasks = taskDao.findAll(); // Fetch all tasks from DB

        for (Task task : allTasks) {
            // Check if any of the task's fields contain the search text (case-insensitive)
            if (task.getName().toLowerCase().contains(searchText) ||
                (task.getAssignedUsername() != null && task.getAssignedUsername().toLowerCase().contains(searchText)) ||
                (task.getBookTitle() != null && task.getBookTitle().toLowerCase().contains(searchText)) ||
                (task.getDeadline() != null && task.getDeadline().toString().toLowerCase().contains(searchText)) ||
                (task.getStatus() != null && task.getStatus().toLowerCase().contains(searchText))) {
                filteredTasks.add(task);
            }
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Task task : filteredTasks) {
            // Add task data to the table: ID (hidden), Task Name, Assigned To, Book Title, Deadline, Status
            model.addRow(new Object[]{
                task.getId(), // Hidden ID
                task.getName(),
                task.getAssignedUsername(),
                task.getBookTitle(),
                task.getDeadline() != null ? task.getDeadline().toString() : "N/A",
                task.getStatus()
            });
        }

    }//GEN-LAST:event_txtSearchFieldActionPerformed

    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) {
            try {
                // Retrieve Task ID from the hidden first column
                int taskId = (int) jTable1.getValueAt(selectedRow, 0);
                Task task = taskDao.findById(taskId); // Fetch task from database

                if (task != null) {
                    String message = String.format(
                        "Task ID: %d\nTask Name: %s\nAssigned To: %s\nBook Title: %s\nDeadline: %s\nStatus: %s\nComment: %s",
                        task.getId(),
                        task.getName(),
                        task.getAssignedUsername(),
                        task.getBookTitle(),
                        task.getDeadline() != null ? task.getDeadline().toString() : "N/A",
                        task.getStatus(),
                        task.getComment() != null ? task.getComment() : "No comment."
                    );
                    JOptionPane.showMessageDialog(this, message, "Task Details", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Selected task not found in the system (database error).", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error retrieving task details: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a task to query.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnQueryActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
       this.dispose();
        // If an admin object exists, pass it back to the dashboard
        if (admin != null) {
            new AdminDashboardFrame(admin).setVisible(true);
        } else {
            // Fallback: If admin object is null, open default AdminDashboard
            new AdminDashboardFrame().setVisible(true);
        } 
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogout3ActionPerformed

    private void btnUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableActionPerformed
     int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(null, "Please select a task to update!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Retrieve Task ID from the hidden first column
            int taskId = (int) jTable1.getValueAt(selectedRowIndex, 0);
            Task selectedTask = taskDao.findById(taskId);

            if (selectedTask == null) {
                JOptionPane.showMessageDialog(null, "Selected task not found in database.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Get new data from the user using input dialogs
            String newTaskName = JOptionPane.showInputDialog(this, "Enter new Task Name:", selectedTask.getName());
            if (newTaskName == null) return; // User cancelled

            String newAssignedToUsername = JOptionPane.showInputDialog(this, "Enter new Assigned To (Username):", selectedTask.getAssignedUsername());
            if (newAssignedToUsername == null) return; // User cancelled

            String newBookTitle = JOptionPane.showInputDialog(this, "Enter new Book Title:", selectedTask.getBookTitle());
            if (newBookTitle == null) return; // User cancelled

            String newDeadlineStr = JOptionPane.showInputDialog(this, "Enter new Deadline (YYYY-MM-DD):", selectedTask.getDeadline().toString());
            if (newDeadlineStr == null) return; // User cancelled

            String newStatus = JOptionPane.showInputDialog(this, "Enter new Status (Pending, In Progress, Completed):", selectedTask.getStatus());
            if (newStatus == null) return; // User cancelled

            // Validate inputs for non-empty fields
            if (newTaskName.trim().isEmpty() || newAssignedToUsername.trim().isEmpty() ||
                newBookTitle.trim().isEmpty() || newDeadlineStr.trim().isEmpty() || newStatus.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled!", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate date format
            LocalDate newDeadlineDate;
            try {
                newDeadlineDate = LocalDate.parse(newDeadlineStr);
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Invalid date format! Please use YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Validate status
            List<String> validStatuses = Arrays.asList("Pending", "In Progress", "Completed");
            if (!validStatuses.contains(newStatus)) {
                JOptionPane.showMessageDialog(this, "Invalid status! Use: Pending, In Progress, or Completed.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Find the User ID for the new assigned username
            User newAssignedUser = userDao.findByUsername(newAssignedToUsername);
            if (newAssignedUser == null) {
                JOptionPane.showMessageDialog(this, "Assigned user '" + newAssignedToUsername + "' not found in the system.", "User Not Found", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Update the Task object with new values
            selectedTask.setName(newTaskName.trim());
            selectedTask.setAssignedTo(newAssignedUser.getId());
            selectedTask.setAssignedUsername(newAssignedUser.getUsername()); // Update assigned username as well
            selectedTask.setBookTitle(newBookTitle.trim());
            selectedTask.setDeadline(newDeadlineDate);
            selectedTask.setStatus(newStatus);

            // Update the task in the database
            taskDao.update(selectedTask);
            JOptionPane.showMessageDialog(this, "Task updated successfully!");

            // Refresh the table to show updated data
            fillTable();

            // Re-select the updated row (if still exists)
            if (selectedRowIndex < jTable1.getRowCount()) {
                jTable1.setRowSelectionInterval(selectedRowIndex, selectedRowIndex);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating task: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllTaskFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllTaskFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnQuery;
    private javax.swing.JButton btnUpdateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSearchField;
    // End of variables declaration//GEN-END:variables




}
